### ISSUE TITLE
CSRF not sent on PUT in API Browser

### ISSUE THREAD

**Issue by MCSH** [encode/django-rest-framework#6873]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create a simple model, serializer, viewset and add it using a router to the urls. Create a user(or superuser).

Create a model instance, browse it using the browser while being logged in and try to update it with PUT.

## Expected behavior

It should update the instance, sending the CSRF token in header.

## Actual behavior
It gives out CSRF exception, and the header is not set.

**Comment by jhonatanlteodoro** [comment]
Someone resolving this?

**Comment by carltongibson** [comment]
Hi @jhonatanlteodoro. I don’t think so currently. If you’d like to investigate it, that would be great!

**Comment by jhonatanlteodoro** [comment]
Hi @carltongibson.
I will investigate this, thanks for answer me.

**Comment by tomchristie** [comment]
The place to start with this would be to investigate if something has changed with sending the CSRF token in the header, which ought to occur automatically for AJAX requests...

https://github.com/encode/django-rest-framework/blob/master/rest_framework/static/rest_framework/js/csrf.js#L43

**Comment by jesteria** [comment]
Just FYI – https://github.com/encode/django-rest-framework/pull/6961#issuecomment-780021026

> The place to start with this would be to investigate if something has changed with sending the CSRF token in the header, which ought to occur automatically for AJAX requests...
> 
> https://github.com/encode/django-rest-framework/blob/master/rest_framework/static/rest_framework/js/csrf.js#L43

**Comment by tomchristie** [comment]
Closing this off, as I can't replicate it...

The X-CSRFToken and Cookie are both being included when I issue PUT requests through the browsable API.

If someone is able to demonstrate that there's an issue here then we can reconsider, but I'd expect us to be getting a *lot* of noise about this if PUT through the browsable API wasn't working.

**Comment by MCSH** [comment]
Are you logged in as I explained?

It's entirely possible that this has been resolved since through another commit. But I do recall that you had to log in in order to see the problem.

**Comment by maycuatroi** [comment]
![image](https://github.com/encode/django-rest-framework/assets/5876946/9e37af14-664d-4b61-9baf-f1b5f9290685)
 This error still happen with PUT request in browser
